name: buf-pull-request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: buf setup action
        uses: bufbuild/buf-setup-action@v1

      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=adapters'
      - uses: bufbuild/buf-push-action@v1
        with:
          input: adapters
          buf_token: ${{ secrets.BUF_TOKEN }}
