name: dispatch run

on:
  repository_dispatch:
    types: [trigger-test]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: print event env
      env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo $EVENT_CONTEXT
    - name: print client_payload
      run: echo ${{ github.event.client_payload }}
    - name: print client_payload example
      run: echo ${{ github.event.client_payload.example }}