name: dispatch run

on:
  repository_dispatch:
    types: [trigger-test]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: print event env
      env:
        EVENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
      run: echo $EVENT_PAYLOAD
